COMP: Fix MSVC build error in encodingZRL.c
This commit fixes a regression introduced in r6219 (first pass at
ZRL decompression).

When building teem using microsoft compiler from vs2008, the following
error was reported:

..\teem\src\nrrd\encodingZRL.c(38) : error C2143: syntax error : missing ';' before 'type'